import type { ApiEndpoint } from '../interfaces.js';

export const ESSENTIAL_APIS: Array<Omit<ApiEndpoint, 'id' | 'createdAt' | 'updatedAt'>> = [
  // ==================== AI/ML ====================
  {
    name: 'OpenAI',
    description: 'GPT models, DALL-E, Whisper, and embeddings API',
    baseUrl: 'https://api.openai.com/v1',
    documentation: 'https://platform.openai.com/docs',
    category: 'ai-ml',
    auth: 'apiKey',
    https: 'yes',
    cors: 'yes',
    priority: 'essential',
    status: 'active',
    tags: ['gpt', 'llm', 'text-generation', 'embeddings', 'images'],
    pricing: { free: false, plans: [{ name: 'Pay-as-you-go', price: 0, period: 'month', requests: 0, features: ['GPT-4', 'GPT-3.5', 'DALL-E', 'Whisper'] }] },
    alternatives: [],
    relatedApis: [],
    lastVerified: new Date(),
  },
  {
    name: 'Anthropic',
    description: 'Claude AI models for text generation and analysis',
    baseUrl: 'https://api.anthropic.com/v1',
    documentation: 'https://docs.anthropic.com',
    category: 'ai-ml',
    auth: 'apiKey',
    https: 'yes',
    cors: 'yes',
    priority: 'essential',
    status: 'active',
    tags: ['claude', 'llm', 'text-generation', 'analysis'],
    pricing: { free: false, plans: [{ name: 'Pay-as-you-go', price: 0, period: 'month', requests: 0, features: ['Claude 3.5', 'Claude 3'] }] },
    alternatives: [],
    relatedApis: [],
    lastVerified: new Date(),
  },
  {
    name: 'Hugging Face',
    description: 'Open-source ML model hub and inference API',
    baseUrl: 'https://api-inference.huggingface.co',
    documentation: 'https://huggingface.co/docs/api-inference',
    category: 'ai-ml',
    auth: 'apiKey',
    https: 'yes',
    cors: 'yes',
    priority: 'essential',
    status: 'active',
    tags: ['models', 'inference', 'nlp', 'vision', 'open-source'],
    pricing: { free: true, freeTierLimit: 1000, plans: [{ name: 'Free', price: 0, period: 'month', requests: 1000, features: ['Inference API', 'Model Hub'] }] },
    alternatives: [],
    relatedApis: [],
    lastVerified: new Date(),
  },

  // ==================== AUTHENTICATION ====================
  {
    name: 'Auth0',
    description: 'Easy to implement, adaptable authentication and authorization platform',
    baseUrl: 'https://dev-{{tenant}}.us.auth0.com/api/v2',
    documentation: 'https://auth0.com/docs',
    category: 'authentication',
    auth: 'apiKey',
    https: 'yes',
    cors: 'yes',
    priority: 'essential',
    status: 'active',
    tags: ['oauth', 'jwt', 'identity', 'sso', 'mfa'],
    pricing: { free: true, freeTierLimit: 7500, plans: [{ name: 'Free', price: 0, period: 'month', requests: 7500, features: ['Universal Login', 'Social Login', 'MFA'] }] },
    alternatives: ['stytch', 'firebase-auth'],
    relatedApis: [],
    lastVerified: new Date(),
  },

  // ==================== EMAIL ====================
  {
    name: 'SendGrid',
    description: 'Email delivery and marketing platform API',
    baseUrl: 'https://api.sendgrid.com/v3',
    documentation: 'https://docs.sendgrid.com',
    category: 'email',
    auth: 'apiKey',
    https: 'yes',
    cors: 'yes',
    priority: 'essential',
    status: 'active',
    tags: ['email', 'smtp', 'marketing', 'transactional'],
    pricing: { free: true, freeTierLimit: 100, plans: [{ name: 'Free', price: 0, period: 'month', requests: 100, features: ['100 emails/day'] }] },
    alternatives: ['mailgun', 'mailjet'],
    relatedApis: [],
    lastVerified: new Date(),
  },
  {
    name: 'Mailgun',
    description: 'Email API service for developers',
    baseUrl: 'https://api.mailgun.net/v3',
    documentation: 'https://documentation.mailgun.com',
    category: 'email',
    auth: 'apiKey',
    https: 'yes',
    cors: 'yes',
    priority: 'essential',
    status: 'active',
    tags: ['email', 'smtp', 'deliverability'],
    pricing: { free: true, freeTierLimit: 1000, plans: [{ name: 'Free', price: 0, period: 'month', requests: 1000, features: ['1,000 emails/month'] }] },
    alternatives: ['sendgrid', 'postmark'],
    relatedApis: [],
    lastVerified: new Date(),
  },

  // ==================== DEVELOPMENT ====================
  {
    name: 'GitHub',
    description: 'Development platform for version control and collaboration',
    baseUrl: 'https://api.github.com',
    documentation: 'https://docs.github.com/rest',
    category: 'development',
    auth: 'oauth',
    https: 'yes',
    cors: 'yes',
    priority: 'essential',
    status: 'active',
    tags: ['git', 'repositories', 'ci', 'collaboration'],
    pricing: { free: true, freeTierLimit: 5000, plans: [{ name: 'Free', price: 0, period: 'month', requests: 5000, features: ['Public repos', 'Issues', 'Actions'] }] },
    alternatives: ['gitlab', 'bitbucket'],
    relatedApis: [],
    lastVerified: new Date(),
  },
  {
    name: 'GitLab',
    description: 'DevOps platform for software development',
    baseUrl: 'https://gitlab.com/api/v4',
    documentation: 'https://docs.gitlab.com/api',
    category: 'development',
    auth: 'oauth',
    https: 'yes',
    cors: 'yes',
    priority: 'essential',
    status: 'active',
    tags: ['git', 'ci', 'devops', 'registry'],
    pricing: { free: true, freeTierLimit: 400, plans: [{ name: 'Free', price: 0, period: 'month', requests: 400, features: ['400 CI mins/month'] }] },
    alternatives: ['github', 'bitbucket'],
    relatedApis: [],
    lastVerified: new Date(),
  },
  {
    name: 'Vercel',
    description: 'Frontend cloud platform for deployment and serverless',
    baseUrl: 'https://api.vercel.com',
    documentation: 'https://vercel.com/docs/rest-api',
    category: 'development',
    auth: 'bearer',
    https: 'yes',
    cors: 'yes',
    priority: 'essential',
    status: 'active',
    tags: ['deploy', 'serverless', 'edge', 'frontend'],
    pricing: { free: true, plans: [{ name: 'Hobby', price: 0, period: 'month', requests: 0, features: ['100GB bandwidth', 'Serverless functions'] }] },
    alternatives: ['netlify', 'cloudflare-pages'],
    relatedApis: [],
    lastVerified: new Date(),
  },

  // ==================== SECURITY ====================
  {
    name: 'VirusTotal',
    description: 'VirusTotal File/URL Analysis for malware detection',
    baseUrl: 'https://www.virustotal.com/api/v3',
    documentation: 'https://docs.virustotal.com',
    category: 'security',
    auth: 'apiKey',
    https: 'yes',
    cors: 'unknown',
    priority: 'essential',
    status: 'active',
    tags: ['malware', 'scan', 'security', 'files', 'urls'],
    pricing: { free: true, freeTierLimit: 500, plans: [{ name: 'Free', price: 0, period: 'month', requests: 500, features: ['500 lookups/day'] }] },
    alternatives: ['abuseipdb'],
    relatedApis: [],
    lastVerified: new Date(),
  },
  {
    name: 'AbuseIPDB',
    description: 'IP/domain/URL reputation checking for security',
    baseUrl: 'https://api.abuseipdb.com/api/v2',
    documentation: 'https://docs.abuseipdb.com',
    category: 'security',
    auth: 'apiKey',
    https: 'yes',
    cors: 'unknown',
    priority: 'essential',
    status: 'active',
    tags: ['ip', 'reputation', 'security', 'threats'],
    pricing: { free: true, freeTierLimit: 1000, plans: [{ name: 'Free', price: 0, period: 'month', requests: 1000, features: ['1,000 checks/day'] }] },
    alternatives: ['virustotal'],
    relatedApis: [],
    lastVerified: new Date(),
  },

  // ==================== GEOCODING ====================
  {
    name: 'Google Maps',
    description: 'Maps, geocoding, directions, and places API',
    baseUrl: 'https://maps.googleapis.com/maps/api',
    documentation: 'https://developers.google.com/maps',
    category: 'geocoding',
    auth: 'apiKey',
    https: 'yes',
    cors: 'unknown',
    priority: 'essential',
    status: 'active',
    tags: ['maps', 'geocoding', 'directions', 'places', 'geolocation'],
    pricing: { free: true, freeTierLimit: 28500, plans: [{ name: 'Free', price: 0, period: 'month', requests: 28500, features: ['Basic map tiles'] }] },
    alternatives: ['mapbox', 'openstreetmap'],
    relatedApis: [],
    lastVerified: new Date(),
  },
  {
    name: 'OpenWeatherMap',
    description: 'Weather data, forecasts, and historical data',
    baseUrl: 'https://api.openweathermap.org/data/2.5',
    documentation: 'https://openweathermap.org/api',
    category: 'weather',
    auth: 'apiKey',
    https: 'yes',
    cors: 'yes',
    priority: 'essential',
    status: 'active',
    tags: ['weather', 'forecast', 'climate', 'temperature'],
    pricing: { free: true, freeTierLimit: 1000, plans: [{ name: 'Free', price: 0, period: 'month', requests: 1000, features: ['1,000 calls/day'] }] },
    alternatives: ['weatherstack', 'accuweather'],
    relatedApis: [],
    lastVerified: new Date(),
  },

  // ==================== FINANCE ====================
  {
    name: 'Stripe',
    description: 'Online payment processing for internet businesses',
    baseUrl: 'https://api.stripe.com/v1',
    documentation: 'https://stripe.com/docs/api',
    category: 'finance',
    auth: 'apiKey',
    https: 'yes',
    cors: 'yes',
    priority: 'essential',
    status: 'active',
    tags: ['payments', 'billing', 'subscriptions', 'invoices'],
    pricing: { free: false, plans: [{ name: 'Pay-as-you-go', price: 0, period: 'month', requests: 0, features: ['2.9% + 30¢ per transaction'] }] },
    alternatives: ['square', 'paypal'],
    relatedApis: [],
    lastVerified: new Date(),
  },
  {
    name: 'Plaid',
    description: 'Financial data API for banking and transactions',
    baseUrl: 'https://production.plaid.com',
    documentation: 'https://plaid.com/docs',
    category: 'finance',
    auth: 'apiKey',
    https: 'yes',
    cors: 'yes',
    priority: 'essential',
    status: 'active',
    tags: ['banking', 'transactions', 'accounts', 'identity'],
    pricing: { free: false, plans: [{ name: 'Pay-as-you-go', price: 0, period: 'month', requests: 0, features: ['Per-API-call pricing'] }] },
    alternatives: [],
    relatedApis: [],
    lastVerified: new Date(),
  },

  // ==================== CLOUD STORAGE ====================
  {
    name: 'AWS S3',
    description: 'Amazon Simple Storage Service for scalable object storage',
    baseUrl: 'https://s3.amazonaws.com',
    documentation: 'https://docs.aws.amazon.com/s3',
    category: 'cloud-storage',
    auth: 'custom',
    https: 'yes',
    cors: 'yes',
    priority: 'essential',
    status: 'active',
    tags: ['storage', 'objects', 'backup', 'cdn'],
    pricing: { free: true, freeTierLimit: 5368709120, plans: [{ name: 'Free Tier', price: 0, period: 'month', requests: 20000, features: ['5GB free for 12 months'] }] },
    alternatives: ['gcs', 'azure-blob'],
    relatedApis: [],
    lastVerified: new Date(),
  },
  {
    name: 'Cloudinary',
    description: 'Image and video management in the cloud',
    baseUrl: 'https://api.cloudinary.com/v1_1',
    documentation: 'https://cloudinary.com/documentation',
    category: 'cloud-storage',
    auth: 'apiKey',
    https: 'yes',
    cors: 'yes',
    priority: 'essential',
    status: 'active',
    tags: ['images', 'video', 'transformation', 'cdn'],
    pricing: { free: true, freeTierLimit: 25000, plans: [{ name: 'Free', price: 0, period: 'month', requests: 25000, features: ['25K transformations/month'] }] },
    alternatives: ['imgix', 'imgbb'],
    relatedApis: [],
    lastVerified: new Date(),
  },

  // ==================== COMMUNICATION ====================
  {
    name: 'Twilio',
    description: 'Communication APIs for SMS, voice, and video',
    baseUrl: 'https://api.twilio.com/2010-04-01',
    documentation: 'https://www.twilio.com/docs',
    category: 'communication',
    auth: 'basic',
    https: 'yes',
    cors: 'yes',
    priority: 'essential',
    status: 'active',
    tags: ['sms', 'voice', 'video', 'whatsapp', 'messaging'],
    pricing: { free: true, freeTierLimit: 15, plans: [{ name: 'Free Trial', price: 0, period: 'month', requests: 15, features: ['$15 trial credit'] }] },
    alternatives: ['vonage', 'messagebird'],
    relatedApis: [],
    lastVerified: new Date(),
  },

  // ==================== BUSINESS ====================
  {
    name: 'Slack',
    description: 'Team messaging and collaboration platform API',
    baseUrl: 'https://slack.com/api',
    documentation: 'https://api.slack.com/docs',
    category: 'business',
    auth: 'oauth',
    https: 'yes',
    cors: 'yes',
    priority: 'essential',
    status: 'active',
    tags: ['messaging', 'collaboration', 'bots', 'webhooks'],
    pricing: { free: true, plans: [{ name: 'Free', price: 0, period: 'month', requests: 0, features: ['Basic messaging'] }] },
    alternatives: ['microsoft-teams', 'discord'],
    relatedApis: [],
    lastVerified: new Date(),
  },
  {
    name: 'Notion',
    description: 'All-in-one workspace for notes, docs, and project management',
    baseUrl: 'https://api.notion.com/v1',
    documentation: 'https://developers.notion.com',
    category: 'business',
    auth: 'bearer',
    https: 'yes',
    cors: 'yes',
    priority: 'essential',
    status: 'active',
    tags: ['notes', 'docs', 'project-management', 'database'],
    pricing: { free: true, plans: [{ name: 'Free', price: 0, period: 'month', requests: 0, features: ['Basic workspace'] }] },
    alternatives: ['confluence', 'coda'],
    relatedApis: [],
    lastVerified: new Date(),
  },

  // ==================== CURRENCY ====================
  {
    name: 'ExchangeRate-API',
    description: 'Free currency conversion and exchange rates',
    baseUrl: 'https://v6.exchangerate-api.com/v6',
    documentation: 'https://www.exchangerate-api.com/docs',
    category: 'currency',
    auth: 'apiKey',
    https: 'yes',
    cors: 'yes',
    priority: 'essential',
    status: 'active',
    tags: ['currency', 'exchange', 'forex', 'conversion'],
    pricing: { free: true, freeTierLimit: 1500, plans: [{ name: 'Free', price: 0, period: 'month', requests: 1500, features: ['1,500 requests/month'] }] },
    alternatives: ['fixer', 'currencylayer'],
    relatedApis: [],
    lastVerified: new Date(),
  },

  // ==================== CALENDAR ====================
  {
    name: 'Google Calendar',
    description: 'Display, create and modify Google calendar events',
    baseUrl: 'https://www.googleapis.com/calendar/v3',
    documentation: 'https://developers.google.com/calendar',
    category: 'calendar',
    auth: 'oauth',
    https: 'yes',
    cors: 'unknown',
    priority: 'essential',
    status: 'active',
    tags: ['calendar', 'events', 'scheduling', 'google'],
    pricing: { free: true, plans: [{ name: 'Free', price: 0, period: 'month', requests: 0, features: ['Basic calendar access'] }] },
    alternatives: ['microsoft-graph-calendar'],
    relatedApis: [],
    lastVerified: new Date(),
  },

  // ==================== WEATHER ====================
  {
    name: 'WeatherAPI',
    description: 'Real-time weather data, forecasts, and historical data',
    baseUrl: 'https://api.weatherapi.com/v1',
    documentation: 'https://www.weatherapi.com/docs',
    category: 'weather',
    auth: 'apiKey',
    https: 'yes',
    cors: 'yes',
    priority: 'essential',
    status: 'active',
    tags: ['weather', 'forecast', 'real-time', 'historical'],
    pricing: { free: true, freeTierLimit: 1000000, plans: [{ name: 'Free', price: 0, period: 'month', requests: 1000000, features: ['1M calls/month'] }] },
    alternatives: ['openweathermap', 'accuweather'],
    relatedApis: [],
    lastVerified: new Date(),
  },
];

export const IMPORTANT_APIS: Array<Omit<ApiEndpoint, 'id' | 'createdAt' | 'updatedAt'>> = [
  // ==================== SOCIAL ====================
  {
    name: 'Twitter/X API',
    description: 'Social media platform API for tweets and user data',
    baseUrl: 'https://api.twitter.com/2',
    documentation: 'https://developer.twitter.com/docs',
    category: 'social',
    auth: 'oauth',
    https: 'yes',
    cors: 'unknown',
    priority: 'important',
    status: 'active',
    tags: ['tweets', 'users', 'social', 'microblogging'],
    pricing: { free: true, freeTierLimit: 500000, plans: [{ name: 'Free', price: 0, period: 'month', requests: 500000, features: ['Basic tweet creation'] }] },
    alternatives: ['mastodon', 'bluesky'],
    relatedApis: [],
    lastVerified: new Date(),
  },
  {
    name: 'Discord',
    description: 'Chat platform API for bots and webhooks',
    baseUrl: 'https://discord.com/api/v10',
    documentation: 'https://discord.com/developers/docs',
    category: 'social',
    auth: 'bearer',
    https: 'yes',
    cors: 'yes',
    priority: 'important',
    status: 'active',
    tags: ['chat', 'bots', 'webhooks', 'gaming'],
    pricing: { free: true, plans: [{ name: 'Free', price: 0, period: 'month', requests: 0, features: ['Bot API', 'Webhooks'] }] },
    alternatives: ['slack', 'telegram'],
    relatedApis: [],
    lastVerified: new Date(),
  },

  // ==================== CRYPTOCURRENCY ====================
  {
    name: 'CoinGecko',
    description: 'Cryptocurrency Price, Market, and Developer/Social Data',
    baseUrl: 'https://api.coingecko.com/api/v3',
    documentation: 'https://www.coingecko.com/api',
    category: 'cryptocurrency',
    auth: 'none',
    https: 'yes',
    cors: 'yes',
    priority: 'important',
    status: 'active',
    tags: ['crypto', 'prices', 'market-data', 'nft'],
    pricing: { free: true, freeTierLimit: 50, plans: [{ name: 'Free', price: 0, period: 'month', requests: 50, features: ['50 calls/minute'] }] },
    alternatives: ['coinmarketcap', 'coincap'],
    relatedApis: [],
    lastVerified: new Date(),
  },
  {
    name: 'CoinMarketCap',
    description: 'Cryptocurrencies Prices and market data',
    baseUrl: 'https://pro-api.coinmarketcap.com/v1',
    documentation: 'https://coinmarketcap.com/api/documentation/v1',
    category: 'cryptocurrency',
    auth: 'apiKey',
    https: 'yes',
    cors: 'unknown',
    priority: 'important',
    status: 'active',
    tags: ['crypto', 'prices', 'market-cap', 'volume'],
    pricing: { free: true, freeTierLimit: 10000, plans: [{ name: 'Basic', price: 0, period: 'month', requests: 10000, features: ['10K credits/month'] }] },
    alternatives: ['coingecko', 'coincap'],
    relatedApis: [],
    lastVerified: new Date(),
  },

  // ==================== TRANSPORTATION ====================
  {
    name: 'Google Maps Routes',
    description: 'Directions and distance matrix API',
    baseUrl: 'https://maps.googleapis.com/maps/api/directions',
    documentation: 'https://developers.google.com/maps/documentation/directions',
    category: 'geocoding',
    auth: 'apiKey',
    https: 'yes',
    cors: 'unknown',
    priority: 'important',
    status: 'active',
    tags: ['directions', 'routes', 'distance', 'navigation'],
    pricing: { free: true, freeTierLimit: 40000, plans: [{ name: 'Free', price: 0, period: 'month', requests: 40000, features: ['40K elements/month'] }] },
    alternatives: ['mapbox-directions', 'openrouteservice'],
    relatedApis: [],
    lastVerified: new Date(),
  },

  // ==================== BOOKS ====================
  {
    name: 'Google Books',
    description: 'Search for books and retrieve book information',
    baseUrl: 'https://www.googleapis.com/books/v1',
    documentation: 'https://developers.google.com/books',
    category: 'books',
    auth: 'apiKey',
    https: 'yes',
    cors: 'unknown',
    priority: 'important',
    status: 'active',
    tags: ['books', 'search', 'metadata', 'volumes'],
    pricing: { free: true, freeTierLimit: 1000, plans: [{ name: 'Free', price: 0, period: 'month', requests: 1000, features: ['1,000 queries/day'] }] },
    alternatives: ['open-library'],
    relatedApis: [],
    lastVerified: new Date(),
  },

  // ==================== NEWS ====================
  {
    name: 'NewsAPI',
    description: 'Search for news articles from worldwide sources',
    baseUrl: 'https://newsapi.org/v2',
    documentation: 'https://newsapi.org/docs',
    category: 'news',
    auth: 'apiKey',
    https: 'yes',
    cors: 'unknown',
    priority: 'important',
    status: 'active',
    tags: ['news', 'articles', 'headlines', 'sources'],
    pricing: { free: true, freeTierLimit: 100, plans: [{ name: 'Free', price: 0, period: 'month', requests: 100, features: ['100 requests/day'] }] },
    alternatives: ['currents-api', 'mediastack'],
    relatedApis: [],
    lastVerified: new Date(),
  },

  // ==================== SPORTS ====================
  {
    name: 'API-Football',
    description: 'Football (soccer) data API with live scores and statistics',
    baseUrl: 'https://v3.football.api-sports.io',
    documentation: 'https://www.api-football.com/documentation-v3',
    category: 'sports',
    auth: 'apiKey',
    https: 'yes',
    cors: 'yes',
    priority: 'important',
    status: 'active',
    tags: ['football', 'soccer', 'scores', 'statistics'],
    pricing: { free: true, freeTierLimit: 100, plans: [{ name: 'Free', price: 0, period: 'month', requests: 100, features: ['100 requests/day'] }] },
    alternatives: ['sportsdata-io'],
    relatedApis: [],
    lastVerified: new Date(),
  },

  // ==================== MUSIC ====================
  {
    name: 'Spotify',
    description: 'Music streaming and metadata API',
    baseUrl: 'https://api.spotify.com/v1',
    documentation: 'https://developer.spotify.com/documentation/web-api',
    category: 'music',
    auth: 'oauth',
    https: 'yes',
    cors: 'yes',
    priority: 'important',
    status: 'active',
    tags: ['music', 'streaming', 'playlists', 'artists'],
    pricing: { free: true, plans: [{ name: 'Free', price: 0, period: 'month', requests: 0, features: ['Basic metadata access'] }] },
    alternatives: ['deezer', 'youtube-music'],
    relatedApis: [],
    lastVerified: new Date(),
  },

  // ==================== GAMES ====================
  {
    name: 'RAWG',
    description: 'Video game database with 500,000+ games',
    baseUrl: 'https://api.rawg.io/api',
    documentation: 'https://rawg.io/apidocs',
    category: 'games',
    auth: 'apiKey',
    https: 'yes',
    cors: 'yes',
    priority: 'important',
    status: 'active',
    tags: ['games', 'database', 'reviews', 'screenshots'],
    pricing: { free: true, freeTierLimit: 20000, plans: [{ name: 'Free', price: 0, period: 'month', requests: 20000, features: ['20K requests/month'] }] },
    alternatives: ['igdb', 'steam'],
    relatedApis: [],
    lastVerified: new Date(),
  },
];

export const ALL_CATALOG_APIS = [...ESSENTIAL_APIS, ...IMPORTANT_APIS];
